<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Mongo.
 * Generated by PHPUnit on 2009-04-09 at 18:09:02.
 */
class CmdSymbolTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Mongo
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    public function setUp() {
        ini_set("mongo.cmd", "!");
        $this->object = $this->sharedFixture->selectCollection('foo', 'bar');
    }

    public function tearDown() {
        $this->object->drop();
    }

    public function testSet() {
        $this->object->save(array('name'=>'google.com'));
        $this->object->update(array(), array('!set' => array("name" => "yahoo.com")));
        $yahoo = $this->object->findOne();
        $this->assertEquals('yahoo.com', $yahoo['name']);

        ini_set("mongo.cmd", "#");
        $this->object->update(array(), array('#set' => array("name" => "askjeeves.com")));
        $jeeves = $this->object->findOne();
        $this->assertEquals('askjeeves.com', $jeeves['name']);
    }

}

?>
