<?php
require_once 'PHPUnit/Framework.php';

require_once 'Mongo/GridFS/File.php';

/**
 * Test class for Mongo.
 * Generated by PHPUnit on 2009-04-09 at 18:09:02.
 */
class MongoGridFSFileTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    MongoGridFSFile
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $db = $this->sharedFixture->selectDB('phpunit');
        $grid = $db->getGridFS();
        $grid->drop();
        $grid->storeFile('./somefile');
        $this->object = $grid->findOne();
        $this->object->start = memory_get_usage(true);
    }

    protected function tearDown() {
        $this->assertEquals($this->object->start, memory_get_usage(true));
    }

    public function testGetFilename() {
        $this->assertEquals($this->object->getFilename(), './somefile');
    }

    public function testGetSize() {
        $size = filesize('./somefile');
        $this->assertEquals($this->object->getSize(), $size);
    }

    public function testWrite() {
        $this->assertFalse(file_exists('./anotherfile'));
        $this->object->write('./anotherfile');
        $this->assertEquals(filesize('./anotherfile'), 
                            $this->object->getSize());

        unlink('./anotherfile');
    }
}
?>
