<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for MongoCode
 * Generated by PHPUnit on 2009-04-10 at 13:30:28.
 */
class MongoCodeTest extends PHPUnit_Framework_TestCase
{
    public function testBasic() {
      $code_str = "if(x<5){ return true; } else { return false;}";

      $c = $this->sharedFixture->selectCollection("x", "y");
      $c->drop();

      $code = new MongoCode($code_str, array());
      $c->insert(array("something" => $code));
      $obj = $c->findOne();
      $this->assertEquals($obj['something']->code, $code_str);
      $this->assertEquals(count($obj['something']->scope), 0);

      $c->remove();
      $code = new MongoCode($code_str, array("x" => 2));
      $c->insert(array("something" => $code));
      $obj = $c->findOne();
      $this->assertEquals($obj['something']->code, $code_str);
      $this->assertEquals(count($obj['something']->scope), 1);
      $this->assertEquals($obj['something']->scope['x'], 2);
      
      $c->remove();
      $code = new MongoCode($code_str);
      $c->insert(array("something" => $code));
      $obj = $c->findOne();
      $this->assertEquals($obj['something']->code, $code_str);
      $this->assertEquals(count($obj['something']->scope), 0);
    }
}

?>
