<?php
require_once 'PHPUnit/Framework.php';

require_once 'Mongo.php';

/**
 * Test class for Mongo.
 * Generated by PHPUnit on 2009-04-10 at 13:30:28.
 */
class MongoCollectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Mongo
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $db = new MongoDB($this->sharedFixture, "phpunit");
        $this->object = $db->selectCollection('c');
        $this->object->drop();
    }

    public function test__toString() {
      $this->assertEquals((string)$this->object, 'phpunit.c');
    }

    public function testDrop() {
      $ns = $this->object->db->selectCollection('system.namespaces');

      $this->object->insert(array('x' => 1));
      $this->object->ensureIndex('x');

      $c = $ns->findOne(array('name' => 'phpunit.c'));
      $this->assertNotNull($c);

      $this->object->drop();

      $c = $ns->findOne(array('name' => 'phpunit.c'));
      $this->assertEquals($c, null);
    }

    public function testValidate() {
      $v = $this->object->validate();
      $this->assertEquals($v['ok'], 0);
      $this->assertEquals($v['errmsg'], 'ns not found');

      $this->object->insert(array('a' => 'foo'));
      $v = $this->object->validate();
      $this->assertEquals($v['ok'], 1);
      $this->assertEquals($v['ns'], 'phpunit.c');
      $this->assertNotNull($v['result']);
    }

    public function testInsert() {
      $a = array("n" => NULL,
                 "l" => 234234124,
                 "d" => 23.23451452,
                 "b" => true,
                 "a" => array("foo"=>"bar",
                              "n" => NULL,
                              "x" => new MongoId("49b6d9fb17330414a0c63102")),
                 "d2" => new MongoDate(1271079861),
                 "regex" => new MongoRegex("/xtz/g"),
                 "_id" => new MongoId("49b6d9fb17330414a0c63101"),
                 "string" => "string");
      
      $this->assertTrue($this->object->insert($a));
      $obj = $this->object->findOne();

      $this->assertEquals($obj['n'], null);
      $this->assertEquals($obj['l'], 234234124);
      $this->assertEquals($obj['d'], 23.23451452);
      $this->assertEquals($obj['b'], true);
      $this->assertEquals($obj['a']['foo'], 'bar');
      $this->assertEquals($obj['a']['n'], null);
      $this->assertNotNull($obj['a']['x']);
      $this->assertEquals($obj['d2']->sec, 1271079);
      $this->assertEquals($obj['d2']->usec, 861000);
      $this->assertEquals($obj['regex']->regex, 'xtz');
      $this->assertEquals($obj['regex']->flags, 'g');
      $this->assertNotNull($obj['_id']);
      $this->assertEquals($obj['string'], 'string');

      $this->assertFalse($this->object->insert(null));
      $this->assertFalse($this->object->insert(array()));
      $this->assertFalse($this->object->insert(1345));
      $this->assertFalse($this->object->insert(true));
      $this->assertTrue($this->object->insert(array(1,2,3,4,5)));
    }

    public function testInsert2() {
      $this->assertFalse($this->object->insert(NULL));
      $this->assertTrue($this->object->insert(array(NULL)));
      $this->assertTrue($this->object->insert(array(NULL=>"1")));
      
      $this->assertEquals($this->object->count(), 2);
      $cursor = $this->object->find();

      $x = $cursor->getNext();
      $this->assertTrue(array_key_exists('0', $x));
      $this->assertEquals($x['0'], null);

      $x = $cursor->getNext();
      $this->assertTrue(array_key_exists('', $x));
      $this->assertEquals($x[''], '1');
    }

    public function testBatchInsert() {
      $this->assertFalse($this->object->batchInsert(null));
      $this->assertFalse($this->object->batchInsert(array()));
      $this->assertFalse($this->object->batchInsert(array(1,2,3)));
      $this->assertTrue($this->object->batchInsert(array('z'=>array('foo'=>'bar'))));

      $a = array( array( "x" => "y"), array( "x"=> "z"), array("x"=>"foo"));
      $this->object->batchInsert($a);
      $this->assertEquals(4, $this->object->count());

      $cursor = $this->object->find()->sort(array("x" => -1));
      $x = $cursor->getNext();
      $this->assertEquals('bar', $x['foo']);
      $x = $cursor->getNext();
      $this->assertEquals('z', $x['x']);
      $x = $cursor->getNext();
      $this->assertEquals('y', $x['x']);
      $x = $cursor->getNext();
      $this->assertEquals('foo', $x['x']);
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testFindException1() {
      $c = $this->object->find(null);
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testFindException2() {
      $c = $this->object->find(3);
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testFindException3() {
      $c = $this->object->find(true);
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testFindException4() {
      $c = $this->object->find(array(), null);
    }

    public function testFind() {
      for ($i=0;$i<50;$i++) {
        $this->object->insert(array('x' => $i));
      }

      $c = $this->object->find();
      $this->assertEquals(iterator_count($c), 50);
      $c = $this->object->find(array());
      $this->assertEquals(iterator_count($c), 50);

      $this->object->insert(array("foo" => "bar",
                                  "a" => "b",
                                  "b" => "c"));

      $c = $this->object->find(array('foo' => 'bar'), array('a'=>1, 'b'=>1));

      $this->assertTrue($c instanceof MongoCursor);
      $obj = $c->getNext();
      $this->assertEquals('b', $obj['a']);
      $this->assertEquals('c', $obj['b']);
      $this->assertEquals(false, array_key_exists('foo', $obj));
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testFindOneException1() {
      $this->object->findOne(true);
    }

    public function testFindOne() {
      $this->assertEquals(null, $this->object->findOne());
      $this->assertEquals(null, $this->object->findOne(array()));

      for ($i=0;$i<3;$i++) {
        $this->object->insert(array('x' => $i));
      }

      $obj = $this->object->findOne();
      $this->assertNotNull($obj);
      $this->assertEquals($obj['x'], 0);

      $obj = $this->object->findOne(array('x' => 1));
      $this->assertNotNull($obj);
      $this->assertEquals(1, $obj['x']);
    }

    public function testUpdate() {
      $old = array("foo"=>"bar", "x"=>"y");
      $new = array("foo"=>"baz");
      
      $this->object->update(array("foo"=>"bar"), $old, true);
      $obj = $this->object->findOne();
      $this->assertEquals($obj['foo'], 'bar');      
      $this->assertEquals($obj['x'], 'y');      

      $this->object->update($old, $new);
      $obj = $this->object->findOne();
      $this->assertEquals($obj['foo'], 'baz');      
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testRemoveException1() {
      $this->object->remove(0);
    }

    public function testRemove() {
      for($i=0;$i<15;$i++) {
        $this->object->insert(array("i"=>$i));
      }
      
      $this->assertEquals($this->object->count(), 15);
      $this->object->remove(array(), true);
      $this->assertEquals($this->object->count(), 14);

      $this->object->remove();
      
      $this->assertEquals($this->object->count(), 0);
    }

    public function testEnsureIndex() {
      $this->object->ensureIndex('foo');

      $idx = $this->object->db->selectCollection('system.indexes');
      $index = $idx->findOne(array('name' => 'foo_1'));

      $this->assertNotNull($index);
      $this->assertEquals($index['key']['foo'], 1);
      $this->assertEquals($index['name'], 'foo_1');

      $this->object->ensureIndex("");
      $index = $idx->findOne(array('name' => '_1'));
      $this->assertNotNull($index);
      $this->assertEquals($index['key'][''], 1);
      $this->assertEquals($index['ns'], 'phpunit.c');

      // get rid of indexes
      $this->object->drop();

      $this->object->ensureIndex(null);
      $index = $idx->findOne(array('name' => '_1'));
      $this->assertNotNull($index);
      $this->assertEquals($index['key'][''], 1);
      $this->assertEquals($index['ns'], 'phpunit.c');

      $this->object->ensureIndex(6);
      $index = $idx->findOne(array('name' => '6_1'));
      $this->assertNotNull($index);
      $this->assertEquals($index['key']['6'], 1);
      $this->assertEquals($index['ns'], 'phpunit.c');

      $this->object->ensureIndex(array('bar' => -1));
      $index = $idx->findOne(array('name' => 'bar_-1'));
      $this->assertNotNull($index);
      $this->assertEquals($index['key']['bar'], -1);
      $this->assertEquals($index['ns'], 'phpunit.c');
    }

    public function testEnsureUniqueIndex() {
      $unique = true;

      $this->object->ensureIndex(array('x'=>1), !$unique);
      $this->object->insert(array('x'=>0, 'z'=>1));
      $this->object->insert(array('x'=>0, 'z'=>2));
      $this->assertEquals($this->object->count(), 2);

      $this->object->ensureIndex(array('z'=>1), $unique);
      $this->object->insert(array('z'=>0));
      $this->object->insert(array('z'=>0));
      $err = $this->sharedFixture->lastError();
      $this->assertEquals($err['err'], "E11000 duplicate key error");
      // this should work, but buildbot says 4
      //$this->assertEquals($this->object->count(), 3);
    }

    public function testDeleteIndex() {
      $idx = $this->object->db->selectCollection('system.indexes');

      $this->object->ensureIndex('foo');
      $this->object->ensureIndex(array('foo' => -1));

      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 3);

      $this->object->deleteIndex(null);
      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 3);

      $this->object->deleteIndex(array('foo' => 1)); 
      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 2);

      $this->object->deleteIndex('foo');
      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 2);

      $this->object->deleteIndex(array('foo' => -1));
      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 1);
    }

    public function testDeleteIndexes() {
      $idx = $this->object->db->selectCollection('system.indexes');

      $this->object->ensureIndex(array('foo' => 1));
      $this->object->ensureIndex(array('foo' => -1));
      $this->object->ensureIndex(array('bar' => 1, 'baz' => -1));

      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 4);

      $this->object->deleteIndexes();
      $num = iterator_count($idx->find(array('ns' => 'phpunit.c')));
      $this->assertEquals($num, 1);
    }

    public function testGetIndexInfo() {
      $info = $this->object->getIndexInfo();
      $this->assertEquals(count($info), 0);

      $this->object->ensureIndex(array('foo' => 1));
      $this->object->ensureIndex(array('foo' => -1));
      $this->object->ensureIndex(array('bar' => 1, 'baz' => -1));

      $info = $this->object->getIndexInfo();
      $this->assertEquals(count($info), 4);
      $this->assertEquals($info[1]['key']['foo'], 1);
      $this->assertEquals($info[1]['name'], 'foo_1');
      $this->assertEquals($info[2]['key']['foo'], -1);
      $this->assertEquals($info[2]['name'], 'foo_-1');
      $this->assertEquals($info[3]['key']['bar'], 1);
      $this->assertEquals($info[3]['key']['baz'], -1);
      $this->assertEquals($info[3]['name'], 'bar_1_baz_-1');
    }

    public function testCount() {
      $this->assertEquals($this->object->count(), 0);

      $this->object->insert(array(6));

      $this->assertEquals($this->object->count(), 1);
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testSaveException1() {
      $this->object->save(null);
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testSaveException2() {
      $this->object->save("");
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testSaveException3() {
      $this->object->save(4);
    }

    public function testSave() {
      $this->object->save(array('x' => 1));
      $a = $this->object->findOne();
      $a['x'] = 2;
      $this->object->save($a);

      $this->assertEquals($this->object->count(), 1);

      $a = $this->object->findOne();
      $this->assertEquals($a['x'], 2);
    }

    public function testGetDBRef() {
        for($i=0;$i<50;$i++) {
            $this->object->insert(array('x' => rand()));
        }
        $obj = $this->object->findOne();

        $ref = $this->object->createDBRef($obj);
        $obj2 = $this->object->getDBRef($ref);

        $this->assertNotNull($obj2);
        $this->assertEquals($obj['x'], $obj2['x']);
    }

    public function testCreateDBRef() {
        $ref = $this->object->createDBRef(array('foo' => 'bar'));
        $this->assertEquals($ref, null);

        $arr = array('_id' => new MongoId());
        $ref = $this->object->createDBRef($arr);
        $this->assertNotNull($ref);
        $this->assertTrue(is_array($ref));

        $arr = array('_id' => 1);
        $ref = $this->object->createDBRef($arr);
        $this->assertNotNull($ref);
        $this->assertTrue(is_array($ref));

        $ref = $this->object->createDBRef(new MongoId());
        $this->assertNotNull($ref);
        $this->assertTrue(is_array($ref));
    }
}
?>
