<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for MongoCollection.
 * Generated by PHPUnit on 2009-04-10 at 13:30:28.
 */
class MongoAuthTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    MongoCollection
     * @access protected
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new MongoAdmin();
        $this->object->login("kristina", "fred");
    }

    protected $object;

    public function testAdminBasic() {
        $this->object->selectCollection("phpunit", "c")->insert(array("foo"=>"bar"));
        $one = $this->object->selectCollection("phpt", "auth.basic")->findOne();
        echo $one["foo"]."\n";
    }

    public function testAddUser() {
        $this->object = new MongoAdmin();
        $this->object->login("kristina", "fred");

        /* check auth methods */
        $this->object->addUser("fred", "ted");
        MongoAuth::getHash("fred", "ted");
        $a2 = new MongoAdmin();
        $a2->login("fred", "ted");
        echo "$a\n";

        var_dump($this->object->changePassword("fred", "ted", "foobar"));

        $a2 = new MongoAdmin();
        $a2->login("fred", "ted");
        var_dump($a2->loggedIn);

        $a2 = new MongoAdmin();
        $a2->login("fred", "foobar");
        var_dump($a2->loggedIn);

        $this->object->deleteUser("fred");
        $a2 = new MongoAdmin();
        $a2->login("fred", "foobar");
        var_dump($a2->loggedIn);
    }
}

?>
