<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Mongo.
 * Generated by PHPUnit on 2009-04-09 at 18:09:02.
 */
class MongoMemTest extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testLastError() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->lastError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testLastError2() {
      $db = $this->sharedFixture->selectDB('db');
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $db->lastError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }
    
    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testPrevError() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->prevError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testPrevError2() {
      $db = $this->sharedFixture->selectDB('db');
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $db->prevError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testResetError() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->resetError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testResetError2() {
      $db = $this->sharedFixture->selectDB('db');
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $db->resetError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testForceError() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->forceError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testForceError2() {
      $db = $this->sharedFixture->selectDB('db');
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $db->forceError();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testSelectDB() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->selectDB("foo");
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testSelectCollection() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->selectCollection("foo", "bar");
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testDropDB() {
      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->dropDB("foo");
      }
      $this->assertEquals($mem, memory_get_usage(true));

      $db = $this->sharedFixture->selectDB("foo");
      for ($i=0;$i<10000;$i++) {
        $this->sharedFixture->dropDB($db);
      }
    }

    public function testGetDBRef() {
      $db = $this->sharedFixture->selectDB("foo");
      $c = $db->selectCollection("bar");
      $obj = array("uid" => 0);
      $c->insert($obj);
      $ref=$c->createDBRef($obj);

      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        MongoDBRef::get($db, $ref);
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function testCreateDBRef() {
      $c = $this->sharedFixture->selectCollection("foo", "bar");
      $obj = array("uid" => 0);
      $c->insert($obj);

      $mem = memory_get_usage(true);
      for ($i=0;$i<10000;$i++) {
        MongoDBRef::create("bar", $obj['_id']);
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }

    public function ensureIndex() {
      $c = $this->sharedFixture->selectCollection("foo", "bar");
      $mem = memory_get_usage(true);
      for ($i=0; $i<10000; $i++) {
        $c->deleteIndexes();
      }
      $this->assertEquals($mem, memory_get_usage(true));
    }
    
}

?>

