<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Mongo.
 * Generated by PHPUnit on 2009-04-09 at 18:09:02.
 */
class MongoUtilTest extends PHPUnit_Framework_TestCase
{
    public function testToIndexString() {
        $this->assertEquals(MongoUtil::toIndexString(null), '_1');
        $this->assertEquals(MongoUtil::toIndexString(52), '52_1');
        $this->assertEquals(MongoUtil::toIndexString('x'), 'x_1');
        $this->assertEquals(MongoUtil::toIndexString('x.y.z'), 'x_y_z_1');
        $this->assertEquals(MongoUtil::toIndexString('x_y.z'), 'x_y_z_1');
        $this->assertEquals(MongoUtil::toIndexString(array('x' => 1)), 'x_1');
        $this->assertEquals(MongoUtil::toIndexString(array('x' => -1)), 'x_-1');
        $this->assertEquals(MongoUtil::toIndexString(array('x' => 1, 'y' => -1)), 'x_1_y_-1');
    }


}
?>

